apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.imageName }}
      ports:
      {{ - range .Values.ports }}
      - containerPort: { { . } }
      {{ - end }}

