apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.imageName }}
      {{ if .Values.openPort }}
      ports:
        - containerPort: 80
      {{ end }}
