apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.imageName }}
      ports:
      {{- range .Values.ports }}
      - containerPort: {{ . }}
      {{- end }}

      env:
      {{- range $k, $v := .Values.env }}
      - name: {{ $k }}
        value: {{ $v }}
      {{- end }}


